server:
  port: 8080
  servlet:
    contextPath: /pokedex

spring:
  profiles:
    active: @spring.profiles.active@
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/pokemon?serverTimezone=UTC
    username: root
  security:
    user:
      name: PikaPika
      password: 12345678

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
